modLoader="javafml"
loaderVersion="[54,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/flur/extrachunky/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="https://github.com/flur/extrachunky"
authors="${author}"
description="${description}"

[[dependencies.extrachunky]]
modId="forge"
mandatory=true
versionRange="[54,)"
ordering="NONE"
side="BOTH"

[[dependencies.extrachunky]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.extrachunky]]
modId="chunky"
mandatory=true
ordering="AFTER"
side="BOTH"
