modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/flur/extrachunky/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="https://github.com/flur/extrachunky"
authors="${author}"
description="${description}"

[[dependencies.extrachunky]]
modId="neoforge"
type="required"
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.extrachunky]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.extrachunky]]
modId="chunky"
type="required"
ordering="AFTER"
side="BOTH"
